### ISSUE TITLE
Do you plan on updating this to the latest version of Ruby, 2.2.2?

### ISSUE THREAD

**Issue by treeder** [GoogleCloudPlatform/ruby-docker#10]
And do you plan on supporting multiple versions of Ruby via tags?

**Comment by dazuma** [comment]
We'll actually be removing the "base", "runtime" and "hello" images shortly (https://github.com/GoogleCloudPlatform/ruby-docker/issues/30). The "appengine" image is currently our supported image, used as the base runtime image for Google AppEngine Flex. We will be keeping it up to date. See http://cloud.google.com/ruby for more info on using the Ruby runtime on Google Cloud.
