### ISSUE TITLE
Cannot use 2 instances in beta_settings cloud_sql_instances

### ISSUE THREAD

**Issue by Nhat002** [GoogleCloudPlatform/ruby-docker#114]
Before today I was able to deploy my app with this setting in `app.yaml` :
```
beta_settings:
    cloud_sql_instances: project-dev:us-region1:database-one,project-dev:us-region1:database-two
```
But today I got this error in docker image build
```Illegal cloud sql instance name: "project:region:database_1,project:region:database_2"```
Are there any changes in cloud_sql_proxy settings? I used a comma-separated list as recommend from here https://cloud.google.com/sql/docs/postgres/sql-proxy and it worked until today.

**Comment by Nhat002** [comment]
I've just edited format of database connection name to be similar to my real connection

**Comment by dazuma** [comment]
There does look like a regression in the parser for the Ruby runtime builder. I pushed a fix into the repo, but we won't be able to do a release until Sept 5, after the holiday.

If you're blocked by this, you can, as a workaround, temporarily revert to the legacy runtime builder by setting:

```
gcloud config set app/use_runtime_builders false
```

**Comment by Nhat002** [comment]
Thank you.

**Comment by hxiong388** [comment]
@Nhat002 We have released a new version of the Ruby runtime builder, which should fix this problem. Please let us know if it works for you.

**Comment by Nhat002** [comment]
@hxiong388  @dazuma It's working fine now. Thanks!

**Comment by dazuma** [comment]
@Nhat002 Great to hear! Thanks for reporting this quickly, and sorry for the hiccup.
