### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by ain** [GoogleCloudPlatform/ruby-docker#144]
Current `ruby` runtime still doesn't have Yarn support.

The topic seems to have been discussed before at https://groups.google.com/forum/#!topic/google-appengine/33xXJ1UZaiQ which refers to the fact that GCP team was working on it. What's the latest status, when could we hope to avoid using custom runtime just for Yarn support?

**Comment by dazuma** [comment]
Yarn should be present—although it is available at build time only (not at runtime). So for example it can be used during asset precompilation, but you cannot call out to it from a Rails controller. Can you provide more specifics about what you are trying to accomplish and what problems you are having?

**Comment by ain** [comment]
Thanks for the response @dazuma, I'll review the CircleCI Workflow to see if our mishap may be in fact caused over a race condition. I suspect we might have an exclusive precompile trigger.

**Comment by ain** [comment]
We were able to leverage build tools during the container build and it did run as hinted. Closing the topic.
