### ISSUE TITLE
app server crashing after bundle

### ISSUE THREAD

**Issue by jgadbois** [GoogleCloudPlatform/ruby-docker#148]
I'm not sure this is a Dockerfile issue, so if not feel free to close this, but when I deploy on app engine flex my webserver is crashing with the following error:

`RuntimeError: Unable to find a spec satisfying rspec-rails (>= 3.5.2) in the set. Perhaps the lockfile is corrupted?`

`rspec-rails` is only configured in development/test groups in the Gemfile and `RAILS_ENV` and `RACK_ENV` are both set to staging so the application should not be looking for rspec-rails.

Is it possible it's the way the Dockerfile is doing the bundle or no?

**Comment by dazuma** [comment]
That's odd. The Dockerfile doesn't do anything particularly odd—just:
```
RUN bundle install --deployment --without="development test"
```

Some things to try:
* Try deleting your Gemfile.lock and regenerating it with `bundle install`.
* Make sure your local bundler is up to date. The Ruby runtime uses bundler 1.16.1 (the latest version) to install your bundle. I suppose it's possible that if you have a really old version of bundler locally, it might be generating a lockfile with some differences.

If you're still seeing this, here are a few questions:
* Are you using a custom runtime (`runtime: custom` where you provide your own Dockerfile) or the official Ruby runtime (`runtime: ruby`)? If you're on a custom runtime, you might consider switching to the official runtime if you can, as its Dockerfile has advanced considerably beyond what is being generated by gen-config.
* Is the error happening during deployment (i.e. during the output of `gcloud app deploy`, which is when the bundle install happens) or is it happening during runtime?
* Would you be okay posting your Gemfile so I can see if something jumps out at me?

**Comment by jgadbois** [comment]
Thanks.  I regenerated `Gemfile.lock` and bundler is also at `1.16.1` on my system.  I'm using the official `ruby` runtime.

The error is happening during runtime (server startup) - our previous host bundled the same way and didn't have this issue and i don't have it running with the staging `RAILS_ENV` and `RACK_ENV` locally either.

As for Gemfile, the only place rspec-rails is specified is:

```
group :development, :test do
  gem 'rspec-rails', '~> 3.5.2'
  gem 'rspec-retry', '~> 0.5.7'
  gem 'better_errors', "~> 1.0.1"
  gem 'rb-fsevent', '~> 0.9.8'
  gem "yard", "~> 0.8.7.3"
  gem 'awesome_print', "~> 1.2.0"
  gem 'dotenv-rails', "~> 0.11.1"
  gem 'spring', "~> 2.0.1"
  gem 'spring-commands-rspec', "~> 1.0.4"
  gem 'guard-rspec', "~> 4.7.3", require: false
  gem "letter_opener", "~> 1.1.2"
end
```

**Comment by jgadbois** [comment]
The runtime error occurs when bundler autoloads the gems:

```
if defined?(Bundler)
  Bundler.require *Rails.groups(:assets => %w(development test))
end
```

Like I said I'm not seeing this on other hosts for some reason.

**Comment by jgadbois** [comment]
I moved some gems around and it appears to be trying to load gems from the development group, so possibly Rails thinks it's in dev mode?  my app.yaml has set

```
  APP_ENV: staging
  RAILS_ENV: staging
  RACK_ENV: staging
```

there's no flags anywhere that assume production or fallback to dev, right?

**Comment by dazuma** [comment]
No there isn't anything that should be falling back to dev. Yeah this one is very puzzling. One thing I'd try is outputting some information over there in your application.rb where the bundler auto-require is done. You can `puts` some things like
* `ENV["RAILS_ENV"]`
* `Rails.env`
* `Rails.groups(:assets => %w(development test).inspect`
* etc.

Then you can see the output in the cloud logger. Go to the cloud console, choose "logging" from the left nav, choose the service (GAE Application, your service, current version), choose "stdout" for the log. You should be able to find the stdout output your Rails app is making when it boots, including the information you printed. That might give some clues as to what it's trying to do.

**Comment by jgadbois** [comment]
I worked around this by pointing foreman to an empty .env file - I'm reaching out to the google support team to figure out why gcloud is ignoring the .gcloudignore - thanks for the help and sorry to bug you!

**Comment by jgadbois** [comment]
Just FYI in case someone else encounters something similar - this is due to a bug in the `gcloud app deploy` code - it's not honoring the .gcloudignore file on deploy - they were able to reproduce on their end.  Recommended workaround is to use `skip_files` in the yaml file.
