### ISSUE TITLE
Read me and explanations

### ISSUE THREAD

**Issue by yjaspar** [GoogleCloudPlatform/ruby-docker#151]
Hi,

I'm trying to put my ruby project on the app engine, but I'm struggling a lot with the configuration and don't know how to troubleshoot / debug the issue.
I actually created a Stackoverflow post with the explanation of the problem.
https://stackoverflow.com/questions/51233614/google-cloud-ruby-deployment-and-ruby-docker

Would it be possible to have a little run down on how to use the tools that you guys are providing in this repo?

I'm not an expert with docker (Yet!) and a little clarity on how to use the different tools would be very useful for me and I'm sure for other people in my situation.

Thank you very much for your awesome work!

**Comment by dazuma** [comment]
I posted you an answer on StackOverflow. Feel free to reach out to me directly if you're still having problems.

I know the code in this repo is difficult to follow. It's the implementation behind the [App Engine Ruby Runtime](https://cloud.google.com/appengine/docs/flexible/ruby/runtime), and I don't expect most users will need to interact with it directly. You're right that the README in this repo could be a bit clearer on that; I'll see about updating it.

**Comment by yjaspar** [comment]
I'm closing this case, and leaving the stackoverflow ticket open for now. I'll try and play a bit with it, if I can't find a solution I'll reach out and if it's solved, then I'll just close that case then 👍 

Thank you very much for your help, it's very useful and well described!
