### ISSUE TITLE
apt-get update fails - Failed to fetch jessie backports repository

### ISSUE THREAD

**Issue by rocketlobster** [GoogleCloudPlatform/ruby-docker#174]
Since the jessie-updates repository [ has been removed](https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html), every attempt to run ```apt-get update``` fails with the following stacktrace:

```
W: Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update -qq && apt-get install liblcms2-utils' returned a non-zero code: 100
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: exit status 100
```
Maybe Google should just re-build and publish one image to fix it for everyone?

**Comment by dazuma** [comment]
How are you reproducing this error? The current image is based on Ubuntu, not Debian, and should not be using Jessie-related repositories at all.
