### ISSUE TITLE
Google Appengine Ruby Docker image is grossly outdated

### ISSUE THREAD

**Issue by romanrev** [GoogleCloudPlatform/ruby-docker#178]
Hello,

The Google built Docker image for Google Appengine Flexible runtime is grossly outdated: the latest image was built on 3 May 2018, almost a year ago:

https://console.cloud.google.com/gcr/images/google-appengine/GLOBAL/ruby?gcrImageListsize=30

The issue with this image is that it relies on the `jessy` Debian release which support has now reached end of life: https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html and any image built on top of that image (`FROM gcr.io/google-appengine/ruby:latest`), will yield this error:

> Failed to fetch http://httpredir.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)

**Comment by dazuma** [comment]
The image you reference is actually not the image currently used by the App Engine flexible runtime. (It's an older image that was used by the runtime until about a year ago, as you mention. The current image is built on Ubuntu.)

**Comment by romanrev** [comment]
@dazuma thanks for your comment, could you explain why the latest image I see at https://console.cloud.google.com/gcr/images/google-appengine/GLOBAL/ruby?gcrImageListsize=30 is from 2018 then? Are you able to point me to the correct Google public GCR repository with the latest Ruby flexible runtime Docker image please?

**Comment by dazuma** [comment]
Again, those images were used by old versions of the Ruby flexible runtime, but are not used by the current runtime. The current runtime images are under https://console.cloud.google.com/gcr/images/gcp-runtimes/GLOBAL/ruby

You generally should not need to use these docker images directly. They are intended to be "internal" to the `runtime: ruby` setup for App Engine. If you want to create a "custom" runtime for a Ruby app, I recommend just using the standard ruby image from DockerHub as a base image.
