### ISSUE TITLE
Plan to update the base OS version?

### ISSUE THREAD

**Issue by knu** [GoogleCloudPlatform/ruby-docker#195]
Thank you for maintaining the Ruby runtime images!  Please allow me to ask a question.  Is there a plan or ongoing project to update the base OS version?

All images are currently based on Ubuntu 16.04 LTS.  It is stable and still works great, but it has been almost five years since it was released and it's becoming outdated [^1], meaning you can use fewer and older packages for your application.  There are already times where you need to manually build and install recent versions of software from the source and its dependencies instead of simply installing prebuilt packages on the fly using apt.

Looking at Circle CI and GitHub Actions, their officially provided docker images are mostly based on Ubuntu 18.04/Debian Buster (default) or Ubuntu 20.04 (experimental).  So, in order to test your application on the same OS as the running environment, you need to prepare and maintain Ubuntu 16.04 based custom images for CI.  This is becoming a burden in development.

I'd much appreciate if Ubuntu 20.04 based images could be provided before 16.04 is considered completely obsolete.  I'm eager to test and submit feedback when beta versions are ready.

[^1]: For the record, it will keep receiving security updates for the next three years until April 2024 through the Extended Security Maintenance period. ([Less than 6 months to Ubuntu 16.04 ESM: 6 things to prepare](https://ubuntu.com/blog/ubuntu-16-04-lts-esm-migration-path))

**Comment by dazuma** [comment]
I have a task to update the base image to 20.04. We'll get that done soon, probably not before the end of April, but this quarter for sure.

**Comment by dazuma** [comment]
Sorry this got pushed down the stack again, but we're finally working on it. See #221

**Comment by knu** [comment]
Thank you so much for the work and your continuous effort!  Unfortunately, the GAE-based Rails app I worked hard on ceased to exist last month due to service/company shutdown, and it's really sad I couldn't get to see it running on the new base image.  I hope other users will benefit a lot from this.  Cheers!
