### ISSUE TITLE
Rack doesn't have a "production" environment

### ISSUE THREAD

**Issue by raggi** [GoogleCloudPlatform/ruby-docker#21]
https://github.com/GoogleCloudPlatform/ruby-docker/blob/master/appengine/Dockerfile#L85

This is a very common Ruby mistake. This environment doesn't exist in Rack, and as a consequence you're missing important middleware, in particular the TempfileReaper.

**Comment by dazuma** [comment]
Fixed as part of https://github.com/GoogleCloudPlatform/ruby-docker/pull/23

**Comment by raggi** [comment]
Please do this as an individual PR

**Comment by dazuma** [comment]
Fixed in #28.
