### ISSUE TITLE
Why not use base ruby images?

### ISSUE THREAD

**Issue by MuhammetDilmac** [GoogleCloudPlatform/ruby-docker#210]
It takes quite a long time to install ruby with rbenv each time. Why not use pre-built ruby images?

**Comment by dazuma** [comment]
The canonical list of prebuilt Ruby versions is actually here: https://github.com/GoogleCloudPlatform/ruby-docker/blob/master/ruby-pipeline/ruby-latest.yaml

Yes, we still need to get 2.6.10, 2.7.6, and 3.0.4 added (as well as 3.1.x). But it's a pretty exhaustive list otherwise.
