### ISSUE TITLE
Is the Ruby version of `ruby-pipeline/ruby-latest.yaml` correct?

### ISSUE THREAD

**Issue by satoshicano** [GoogleCloudPlatform/ruby-docker#214]
In #212, some versions has been added, but it looks like the version is wrong.

Specifically, it is on the following line. (Isn't it correct 2.6.9?)

https://github.com/GoogleCloudPlatform/ruby-docker/blob/ca02007c83a9bd146cb4415115a455ce56a13cc7/ruby-pipeline/ruby-latest.yaml#L64

Is this a deliberate change?

If not, is it okay to create a PR?

**Comment by amurciasu** [comment]
You are right.

https://github.com/GoogleCloudPlatform/ruby-docker/pull/215

**Comment by dazuma** [comment]
Thanks for catching this. I merged the PR and will rebuild the runtime within the next day.

**Comment by dazuma** [comment]
Was able to expedite the runtime release. This should be fixed now. Apologies for the typo!

**Comment by satoshicano** [comment]
Thanks all for the lighting fast release!
