### ISSUE TITLE
Running autoconf should not be necessary

### ISSUE THREAD

**Issue by raggi** [GoogleCloudPlatform/ruby-docker#22]
https://github.com/GoogleCloudPlatform/ruby-docker/blob/master/base/Dockerfile#L25

The ruby package provides a working configure script. Running autoconf shouldn't be needed when using the release tarballs.

**Comment by dazuma** [comment]
We'll be removing the "base", "runtime" and "hello" images soon (https://github.com/GoogleCloudPlatform/ruby-docker/issues/30). Only the "appengine" image will be maintained going forward.
