### ISSUE TITLE
unable to deploy due to persistent rubygems timeout

### ISSUE THREAD

**Issue by samkelly** [GoogleCloudPlatform/ruby-docker#82]
This started happening today. Every time I try to deploy, I get an error like the following during the gem installation phase:

```
...
Installing rly 0.2.3
Installing zonefile 1.04
Installing stackdriver-core 0.21.0
Installing libv8 3.16.14.19 (x86_64-linux)
Installing rb-fsevent 0.9.8
Installing netrc 0.11.0
Installing mysql2 0.4.5 with native extensions
Installing puma 3.8.2 with native extensions
Using bundler 1.14.3
Installing redcarpet 3.4.0 with native extensions
Installing ref 2.0.0
Installing rspec-support 3.5.0
Installing rubyzip 1.2.1
Installing sass 3.4.23
Installing tilt 2.0.7
Installing websocket 1.2.4
Installing temple 0.7.7
Installing faker 1.7.3
Installing tzinfo 1.2.2
Installing nokogiri 1.7.1 with native extensions
Installing rack-test 0.6.3
Installing sprockets 3.7.1
Installing websocket-driver 0.6.5 with native extensions
Installing mime-types 3.1
Installing addressable 2.5.0
Installing childprocess 0.6.2
Gem::RemoteFetcher::UnknownHostError: timed out
(https://rubygems.org/gems/coffee-script-source-1.12.2.gem)
An error occurred while installing coffee-script-source (1.12.2), and Bundler
cannot continue.
Make sure that `gem install coffee-script-source -v '1.12.2'` succeeds before
bundling.
The command '/bin/sh -c bundle install && rbenv rehash' returned a non-zero code: 5
ERROR
ERROR: build step "gcr.io/cloud-builders/docker@sha256:fbdb50a2d9d93916ae0193abfd4796f4b580143f60a9406e546906c9bbe768a0" failed: exit status 5
ERROR: (gcloud.app.deploy) Error Response: [2] Build failed; check build logs for details
```

Every time it happens it is a different gem that times out. At first I was thinking maybe rubygems or google was having network issues, but it fails so consistently that I think maybe something else is wrong. It's been about a month since I deployed, so maybe some change has messed this up?

note: I am using the flexible app engine,

Here is my Dockerfile:
```
FROM gcr.io/google_appengine/ruby
RUN apt-get update -y && \
    apt-get install -y -q --no-install-recommends \
        libqtwebkit-dev \
        gstreamer1.0-plugins-base \
        gstreamer1.0-tools \
        gstreamer1.0-x
COPY Gemfile Gemfile.lock /app/
RUN bundle install && rbenv rehash
COPY . /app/
```

Here is my Gemfile:
```ruby
source 'http://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'activerecord'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'bcrypt', '~> 3.1.7'
gem 'slim-rails'
gem 'google-cloud'
gem 'font-awesome-rails'
gem 'httpclient'
gem 'faraday'
gem 'rest-client'
gem 'github-markup'
gem 'redcarpet'
gem 'gon'
gem 'gibberish'
gem 'therubyracer'
gem 'mailgun_rails'
gem 'faker'
gem 'factory_girl_rails'
gem 'stackdriver'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'rspec-rails'
  gem 'rack-test'
  gem 'selenium-webdriver'
  gem 'capybara-webkit'
  gem 'capybara-email'
  gem 'timecop'
  gem 'letter_opener'
  gem 'awesome_print'
  gem 'database_cleaner'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

Here is my gcloud version:
```
sam:~$ gcloud --version
Google Cloud SDK 147.0.0
alpha 2017.03.13
beta 2017.03.13
bq 2.0.24
bq-nix 2.0.24
core 2017.03.13
core-nix 2017.03.13
gcloud 
gcloud-deps 2017.03.13
gcloud-deps-linux-x86_64 2017.03.13
gsutil 4.22
gsutil-nix 4.22
```

Here is my Gemfile.lock:
http://pastebin.com/2vm0QFTu

Here is my app.yaml file:
```
runtime: custom
env: flex
entrypoint: bundle exec rackup -p 8080 -E production config.ru

resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5
```

@dazuma 

moved from: https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1344#issuecomment-287860801

**Comment by dazuma** [comment]
@samkelly Thanks for the detailed report. I'll try to reproduce your issue, but first here are a few things to try:

* Use `source 'https://rubygems.org'` (i.e. https instead of http) in your Gemfile. That form is recommended by bundler, and I vaguely remember running into some similar apparent network issues with gem installs several (like ~5) years ago when using the non-secure URL.
* In your custom Dockerfile, make sure you set a CMD or ENTRYPOINT. Recent versions of the ruby base image don't have a default, and require your derived image to set it. You can use this line:
```
CMD ["bundle", "exec", "rackup", "-p", "8080", "-E", "production", "config.ru"]
```
* Try upgrading bundler in your Dockerfile. (The base image currently has 1.14.3; the latest is 1.14.6. I'm in the process of getting the base image updated, but it'll be another day or two.) Easiest way to do this is to add this line before the bundle install:
```
RUN gem install bundler
```

**Comment by samkelly** [comment]
note: if there was a way for me to specify `bundle install --without development test` instead of standard `bundle install`, I could avoid using a custom Dockerfile -- reason I need it is capybara-webkit (used for specs) needs qt installed and has a bunch of other dependencies. I don't need these on production.

note: I'm trying a different Dockerfile right now that does `bundle install --without development test` so I can skip the apt-get stuff

**Comment by samkelly** [comment]
as it turns out, when the apt-get section is not in my Dockerfile, there are no timeout issues with rubygems... maybe there is some sort of bandwidth constraint on the whole process

will let you know in a few mins of the deploy works -- right now it's spinning at `Updating service [default]` for the last 10 mins.

**Comment by dazuma** [comment]
@samkelly 

> note: if there was a way for me to specify bundle install --without development test instead of standard bundle install, I could avoid using a custom Dockerfile -- reason I need it is capybara-webkit (used for specs) needs qt installed and has a bunch of other dependencies. I don't need these on production.

Oh really? In that case, you should be able to drop the custom Dockerfile completely, because the standard Ruby runtime already does `bundle install --deployment --without="development test"`. In your `app.yaml` file, change `runtime: custom` to `runtime: ruby`, and delete (or move out of the way) the custom Dockerfile.

**Comment by samkelly** [comment]
@dazuma oh that's great! back a couple of months I guess that wasn't the case, which is why I've ended up in this cycle of unsustainable Dockerfile changes

**Comment by samkelly** [comment]
@dazuma ok using the default runtime: ruby option it gets all the way to `Updating service [default]...` and then spins seemingly forever. It's been about 10 minutes of spinning.

**Comment by dazuma** [comment]
@samkelly Give it a few more minutes. It should normally take between 5-7 minutes but I've seen it take 20 mins or more (ugh).

**Comment by samkelly** [comment]
@dazuma yes this has been my experience as well -- I actually always have to set the default gcloud app deploy timeout to about 30 mins. Is there a reason it is so slow with ruby?

**Comment by samkelly** [comment]
@dazuma it worked!!

two questions:
1. it prompted me for the entrypoint when I deployed -- can I hard code this in the app.yaml file, and if so, what would the syntax be?
2. During deployment I am getting the following stackdriver error. Is there a way I can fix this? I feel like every time I deploy I have to re-enable stackdriver.

```
...
Step 7 : ENV RACK_ENV production RAILS_ENV production RAILS_SERVE_STATIC_FILES true
 ---> Running in a870979c9e9b
 ---> 071b3ca01257
Removing intermediate container a870979c9e9b
Step 8 : RUN if test -d app/assets -a -f config/application.rb; then       bundle exec rake assets:precompile || true;     fi
 ---> Running in ba6405b34b54
Google::Cloud::Logging is not activated due to authorization error: Error code 404 trying to get security access token
from Compute Engine metadata for the default service account. This
may be because the virtual machine instance does not have permission
scopes specified.

Falling back to default logger
Unable to initialize Google::Cloud::Trace due to authorization error: Error code 404 trying to get security access token
from Compute Engine metadata for the default service account. This
may be because the virtual machine instance does not have permission
scopes specified.
I, [2017-03-21T01:36:09.500853 #5]  INFO -- : Writing /app/public/assets/force_ssl-e64dd324d605e77af1f21b2c3bc998f04b08c0087cfced1cdc8f36929a51fbfa.js
I, [2017-03-21T01:36:09.501957 #5]  INFO -- : Writing /app/public/assets/force_ssl-e64dd324d605e77af1f21b2c3bc998f04b08c0087cfced1cdc8f36929a51fbfa.js.gz
I, [2017-03-21T01:36:09.650467 #5]  INFO -- : Writing /app/public/assets/application-bb92c96c5c644a0b9d215780383634f7fcb8738b883a07fa66f39abbcc4d795d.js
I, [2017-03-21T01:36:09.651711 #5]  INFO -- : Writing /app/public/assets/application-bb92c96c5c644a0b9d215780383634f7fcb8738b883a07fa66f39abbcc4d795d.js.gz
I, [2017-03-21T01:36:10.389489 #5]  INFO -- : Writing /app/public/assets/application-e46dd1151844412406749febd139481bc1da6abdb4f5b1248331ed06a032842d.css
I, [2017-03-21T01:36:10.390554 #5]  INFO -- : Writing /app/public/assets/application-e46dd1151844412406749febd139481bc1da6abdb4f5b1248331ed06a032842d.css.gz
I, [2017-03-21T01:36:10.391284 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot
I, [2017-03-21T01:36:10.394966 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-7bfcab6db99d5cfbf1705ca0536ddc78585432cc5fa41bbd7ad0f009033b2979.eot.gz
I, [2017-03-21T01:36:10.396230 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-2adefcbc041e7d18fcf2d417879dc5a09997aa64d675b7a3c4b6ce33da13f3fe.woff2
I, [2017-03-21T01:36:10.400494 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-ba0c59deb5450f5cb41b3f93609ee2d0d995415877ddfa223e8a8a7533474f07.woff
I, [2017-03-21T01:36:10.401778 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf
I, [2017-03-21T01:36:10.402774 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-aa58f33f239a0fb02f5c7a6c45c043d7a9ac9a093335806694ecd6d4edc0d6a8.ttf.gz
I, [2017-03-21T01:36:10.403448 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg
I, [2017-03-21T01:36:10.408663 #5]  INFO -- : Writing /app/public/assets/fontawesome-webfont-ad6157926c1622ba4e1d03d478f1541368524bfc46f51e42fe0d945f7ef323e4.svg.gz
 ---> 64d94ce18692
Removing intermediate container ba6405b34b54
Step 9 : ENTRYPOINT 
 ---> Running in 84d548219acc
 ---> 58651ef3f201
Removing intermediate container 84d548219acc
Step 10 : CMD bundle exec rackup -p $PORT
 ---> Running in 5c2234a06809
 ---> 1d397137998d
Removing intermediate container 5c2234a06809
Successfully built 1d397137998d
PUSH
...
```

**Comment by dazuma** [comment]
@samkelly 

It's been slow across the board, regardless of language. I don't think there's anything making Ruby specifically any worse. There's a big internal effort to improve the performance of that "service updating" phase, and it's been improving, but... slowly... :-/

Regarding entrypoint, the syntax in the `app.yaml` file you have above is correct. If that `entrypoint:` line is present, gcloud should pick it up rather than prompting you. Is it still there?

Those stackdriver warnings are harmless, but---you're right---annoying and misleading. They're happening because we try to precompile your Rails assets (which starts the Rails environment) during the build of your app's Docker image, and the VM running the build doesn't have access to your Stackdriver account. It's a known issue, and it'll go away soon when we finish a bunch of improvements we're working on to the build system.

**Comment by samkelly** [comment]
ok thanks!
