### ISSUE TITLE
Can't figure out how to install additional packages

### ISSUE THREAD

**Issue by bogdan-dumitru** [GoogleCloudPlatform/ruby-docker#90]
I'm pretty new at GoogleCloud and I've been trying to figure out how to deploy a ruby instance that requires some extra linux packages to be installed.

I was going through the motion of copying the Dockerfile that gets generated when I noticed this ``packages`` attribute that would be exactly what I need but I can't seam to trace it back to the yaml configuration file I provide or find anything in documentation about it.

```
# Installs additional Debian packages requested.
RUN if test -n "$ADDITIONAL_PACKAGES"; then \
      apt-get install -y -q $ADDITIONAL_PACKAGES; \
    fi
```

If I try to add a "packages" attribute to the app.yaml I get that it's unexpected.
Is this feature not enabled yet throughout the whole stack? 

Thanks for the help!

**Comment by hxiong388** [comment]
@bogdan-dumitru I think the workflow you're using is Google App Engine (GAE). This [code](https://cloud.google.com/appengine/docs/flexible/ruby/runtime) you were referring is staging code that's still WIP. It's not used by the current GAE workflow yet.

To customize the runtime docker image to add more debian packages, follow the instruction on this [doc](https://cloud.google.com/appengine/docs/flexible/ruby/runtime). The "Extending the runtime" section explains how to create your own runtime image for GAE. 

Alternatively, if you need more control over your runtime Docker image. You may also consider using [Google Container Engine](https://cloud.google.com/container-engine/).

**Comment by bogdan-dumitru** [comment]
@hxiong388 Got it yeah, I ended up creating a custom runtime and it works well, was just wondering if I can avoid that with that specific setting. Cool, thanks for the reply!
